package contants;

public class OffersContants {
	public static  String OFFERSTXTCROLL ="OFFERS";
	public static  String CANCELSCROLL = "Cancel and return to ESSO";
	public static  String NECTARCARDTRANSTXT ="Card added successfully, you will start\n earning points. You need to verify your\n card to see your exclusive rewards.";
	public static String LINKACCPOPUPTXT = "Your card will not be linked and you won’t be able to \nspend your Nectar points with ESSO";
	public static String STATIONOFFERTTL = "Fuel at MRH GOODMAYES";
	public static String STATIONOFFERDES = "See current promotions and rewards when you log into the app!";
	public static String HIW = "How It Works";
	public static String ADDNECTAR = "Add Nectar Card";
	public static String NECTARNUM = "46362546029";
	public static String NECTARNUMVALID = "46362546029";
	public static String NECTARPASS = "Nectar123*";
	public static String OTP = "960884";
	public static String APPLY1 = "APPLY 1 FILTER";
	public static String OFFNOTETTL = "How to get this offer";
	public static String OFFTCDES = "1. Offer valid on the first qualifying transaction after Loading to card 2. Bonus points will only be awarded to the registered account holder of the Nectar card presented at the time of the Qualifying Purchase. 3. Bonus points are non-transferable and there are no cash or prize alternatives available. Your statutory rights are not affected. 4. Points will be awarded within 28 days of offer expiry.";
	public static String OFFNOTEDES = "1. Click 'Load to Card'\n2. Fill up at least 20 litres at a participating Esso branded service station\n3. Swipe your Nectar card at the point of pay";
	public static String CPNECTTTL = "Esso Nectar";
	public static String CPNECTDES = "You can collect Nectar and get exclusive rewards.";
	public static String OFFERSCROLL = "\"View Offer\"";
	public static String NOREDEMPTION = "Sorry, there are no redemption options available for you at the moment. Keep fuelling to earn exciting rewards!";
	public static String AUTHTTL = "Please wait";
	public static String TRANSCOMPADDNECT = "Add your Nectar card to get\nexclusive Esso rewards.";
	public static String AUTHDES = "Authorising your payment";
	public static String STARTNOW = "Start fuelling now";
	public static String VERIFYTTL = "Verify Card";
	public static String VERIFYDES = "Your card number has been added but\nyou must verify it with Nectar to enjoy\nthe benefits of exclusive rewards.";
	public static String ADDNECTARHEAD = "Add Nectar Card";
	public static String ADDNECTARHEADIOS = "Enter Nectar Card Details";
	public static String CONTINUE = "//android.widget.Button[@text='Continue']";
	public static String CARDNUM = "****6060";
	public static String COLECTMOREHEAD = "COLLECT MORE NECTAR POINTS";
	public static String FINDMORELNK = "Find out more about Nectar";
	public static String COLLECTPTSLNK = "Collect points";
	public static String OFFERSFINDSCROLL = "Find out more about Nectar";
	public static String NECTARCARDNUMBERINLINEERRORMSG = "Please enter a Nectar Card number";
	public static String STATIONOFFERDES1 = "Go further when you turn your Nectar points into fuel! \nRedeem points for 5p off per litre today!";
}